### PR TITLE
fix: fix package.json exports

### PR DESCRIPTION
**Pull request by hmbrg**
I've way too much time trying to figure this out...

I was trying to import the package but got the common “module not found” error. Eventually, figuring out the package.json had this small error.

### CODE REVIEW

**Comment by clarkbw** [comment]
I ran into this same issue, thank you for this fix!

**Comment by clarkbw** [comment]
Looks like upgrading to pnpm v9 caused this https://github.com/paambaati/neon-js-sdk/commit/4e20738f08c47fefeb20776d1f33ffdc12739e45

**Comment by clarkbw** [comment]
for now, i'm running pinned to `v1.23.0`

```typescript
import { NeonClient } from "npm:neon-sdk@1.23.0";
```

or more simply in deno import maps

```json
{
  "imports": {
    "npm:neon-sdk": "npm:neon-sdk@1.23.0"
  }
}
```

**Comment by paambaati** [comment]
Thanks for the PR, @hmbrg; I'm surprised the `publint` package did not catch this.

**Comment by paambaati** [comment]
This PR is merged but a fix with this is not yet published because I seem to be having [problems with provenance](https://github.com/paambaati/neon-js-sdk/actions/runs/10991243928/job/30513206681); I'm following up with GitHub for an issue resolution. Thanks for your patience!

**Pull request merged**
